// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    createdat,
    updatedat,
    email
) VALUES (get_random_uuid(), now(), now(), $1)
RETURNING id, email, createdat, updatedat
`

func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
